---

- src: https://github.com/joalon/strongswan-vpn/
  name: strongswan-vpn

- src: https://github.com/joalon/dhcp/
  name: dhcp

- src: https://github.com/joalon/yum/
  name: yum

- src: https://github.com/joalon/bind-dns/
  name: bind-dns

- src: https://github.com/joalon/setup-and-hardening/
  name: setup-and-hardening

